Vagrant.configure("2") do |config|
  config.vm.box = "fedora-44"

#  config.vm.network "private_network", ip: "192.168.121.146"
  
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/playbook.yml"
  end
end

